<?php  exit();
/*
Page: /ecititcms/dede/member_guestbook.php
Error: Table 'ecititcms.ecit_it_member_guestbook' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM ecit_it_member_guestbook AS g LEFT JOIN ecit_it_member AS m ON g.mid=m.mid WHERE 1=1 LIMIT 0,1;</font>
Time2013-06-10 10:48:05
*/
?>
<?php  exit();
/*
Page: /ecititcms/dede/member_guestbook.php
Error: Table 'ecititcms.ecit_it_member_guestbook' doesn't exist <br />Error sql: <font color='red'>SELECT g.*,m.userid FROM ecit_it_member_guestbook AS g LEFT JOIN ecit_it_member AS m ON g.mid=m.mid WHERE 1=1  ORDER BY aid DESC LIMIT 0,20</font>
Time2013-06-10 10:48:05
*/
?>
<?php  exit();
/*
Page: /ecititcms/dede/member_operations.php
Error: Table 'ecititcms.ecit_it_member_operation' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `ecit_it_member_operation`  WHERE buyid LIKE '%%' LIMIT 0,1;</font>
Time2013-06-10 10:48:15
*/
?>
<?php  exit();
/*
Page: /ecititcms/dede/member_operations.php
Error: Table 'ecititcms.ecit_it_member_operation' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `ecit_it_member_operation`  WHERE buyid LIKE '%%'  ORDER BY aid DESC LIMIT 0,25</font>
Time2013-06-10 10:48:15
*/
?>
<?php  exit();
/*
Page: /ecititcms/dede/shops_operations.php
Error: Table 'ecititcms.ecit_it_shops_userinfo' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM ecit_it_shops_orders AS s LEFT JOIN ecit_it_shops_userinfo AS u ON s.oid=u.oid LIMIT 0,1;</font>
Time2013-06-10 10:48:16
*/
?>
<?php  exit();
/*
Page: /ecititcms/dede/shops_operations.php
Error: Table 'ecititcms.ecit_it_shops_userinfo' doesn't exist <br />Error sql: <font color='red'>SELECT s.`oid`,s.`cartcount`,s.`price`,s.`state`,s.`stime`,s.priceCount,s.dprice,s.paytype,u.`consignee`,u.`tel`,s.`userid` FROM ecit_it_shops_orders AS s LEFT JOIN ecit_it_shops_userinfo AS u ON s.oid=u.oid  ORDER BY `stime` DESC LIMIT 0,25</font>
Time2013-06-10 10:48:16
*/
?>
<?php  exit();
/*
Page: /ecititcms/dede/sys_payment.php
Error: Table 'ecititcms.ecit_it_payment' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `ecit_it_payment` LIMIT 0,1;</font>
Time2013-06-10 10:48:17
*/
?>
<?php  exit();
/*
Page: /ecititcms/dede/sys_payment.php
Error: Table 'ecititcms.ecit_it_payment' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `ecit_it_payment` ORDER BY rank ASC LIMIT 0,25</font>
Time2013-06-10 10:48:17
*/
?>
